### ISSUE TITLE
Add BDD tests for wfAPI

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/workflow-component#20]
#### Description:
The gist of the tests:

- [ ] add new pipeline to UV using UV-API - not possible due to UnifiedViews 2.3.0
- [x] check results through wfAPI
- [x] run pipeline in UV
- [x] check results through wfAPI

#### DoD:

- [x] BDD tests available in wf-feature-tests
- [x] WF-API Unit tests

#### Testing:
Peer Review

**Comment by blankdots** [comment]
Functionalities for:
* run pipeline
* add new pipeline  - requires: https://github.com/ATTX-project/workflow-component/issues/32
* check results
have been implemented in https://github.com/ATTX-project/graph-component/issues/6

**Comment by blankdots** [comment]
BDD tests have been done in https://github.com/ATTX-project/project-management/issues/68

**Comment by blankdots** [comment]
```
--------------- coverage: platform linux2, python 2.7.6-final-0 ----------------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
src/wf_api/__init__                   0      0   100%
src/wf_api/api/__init__               0      0   100%
src/wf_api/api/activity              32      6    81%
src/wf_api/api/workflow              32      6    81%
src/wf_api/app                        8      2    75%
src/wf_api/utils/__init__             2      0   100%
src/wf_api/utils/db                  16      3    81%
src/wf_api/utils/logs                 6      0   100%
src/wf_api/utils/prefixes            14      0   100%
src/wf_api/uv/__init__                0      0   100%
src/wf_api/uv/activity_metadata      67      5    93%
src/wf_api/uv/parse_config           50      0   100%
src/wf_api/uv/workflow_metadata      66      5    92%
src/wf_api/wfapi                     29      6    79%
-----------------------------------------------------
TOTAL                               322     33    90%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```
90% coverage achieved.
in order to generate coverage report run `gradle :wf-API:pytest coverage`
