### ISSUE TITLE
Create a new custom image with ATTX specific DPUs and add it to the uv-compose

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/workflow-component#22]
#### Description
Basically the same thing as with the built-in DPUs, but just contains our own jars.
*.jar files are fetched from external source - where Jenkins/CI placed the artefacts (e.g. Nexus repository, or folder accessible via HTTP).
Related ATTX-project/project-management#57
#### DoD
Docker image that contains all ATTX related DPUs - `attxproject/uv-attx-dpus`
UV-docker-compose works with the new docker image.
#### Testing
BDD Testing using UnifiedVIews REST API

**Comment by blankdots** [comment]
https://grips.semantic-web.at/display/UDDOC/UnifiedViews+REST+API#UnifiedViewsRESTAPI-6.1ImportDPU
