### ISSUE TITLE
BUG: related to adding ATTXMetadataDPU to the pipeline.

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#26]
#### Description
The bug appears when deleting and adding again to a different pipeline.
#### DoD
Fix bug as it is annoying, and works with all other components.
#### Testing
Peer Review.

**Comment by blankdots** [comment]
It seems that the ATTXMetadata DPU is not properly added (or persistent) to the front end using the command:
`docker run --rm -v <source folder>:/dpus --link <name of the image>:frontend tenforce/unified-views-add-dpus`
After a restart of the docker compose it seems like the plugin is not there anymore:
* in the running container check it in `/unifiedviews/dpu` folder

The cause ~~might be the name related or something different and it needs further testing.~~ might be by the add-dpu tenforce image which overwrites the plugin folder on every restart of the docker image.

**Comment by jkesanie** [comment]
See if this can be replicated after completing ATTX-project/workflow-component#22

**Comment by blankdots** [comment]
Tried replicating after the fix with the new docker-compose after  ATTX-project/workflow-component#22 but does not appear there.
