### ISSUE TITLE
Configure Download DPU for Infrastructure UC

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#30]
#### Description
Configure Download DPU for Infrastructure UC.
#### DoD
UC related workflows have the data available in UnifiedViews. Transformations in #28 and #29
#### Testing
Peer review

**Comment by blankdots** [comment]
available in the Sandbox environment

**Comment by jkesanie** [comment]
Changed testing to peer review, because we need the newer version of the UnifiedViews (with working workflow upload) in order to make the BDD tests.
