### ISSUE TITLE
Configure Upload DPU for Infrastructure UC

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#31]
#### Description
Configure Upload DPU for Infrastructure UC
#### DoD
Upload the data to the Graph Store in specific context.
#### Testing
Peer review

**Comment by blankdots** [comment]
available in the Sandbox environment

**Comment by jkesanie** [comment]
Changed testing to peer review, because we need the newer version of the UnifiedViews (with working workflow upload) in order to make the BDD tests.

**Comment by jkesanie** [comment]
This required new dpu for uploading data to Fuseki.
https://github.com/ATTX-project/workflow-component/tree/dev/unifiedViews/uv-dpu-l-attx-uploader
