### ISSUE TITLE
Custom config images for UnifiedViews

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/workflow-component#34]
#### Description
We need our own images for configs.
#### DoD

- [x] Custom configs are in place and functional.
- [x] There is a Jenkins task that generates the new image in our private repository.

#### Testing
Peer review

**Comment by joasilva** [comment]
Gradle build and Dockerfiles here: https://github.com/ATTX-project/platform-deployment/tree/feature-custom-shell-script

Jenkins job: http://attx-dev:49001/job/uv-attx-shared-image/
