### ISSUE TITLE
Verify that the current UnifiedViews endpoint add Pipelines is not working

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#39]
#### Description
We want to verify the assumption in order to do the version bump.
#### DoD
Decision to proceed or not.
#### Testing
Add Tests

**Comment by jkesanie** [comment]
Current version of the UnifiedViews is actually working for our use cases (testing) using 
these two endpoints:

/master/api/1/pipelines/import
Body (form-data):
file: 
importUserData: true/false
importSchedule: true/false

/master/api/1/pipelines/{pipelineID}/executions
Body (json):
{
    "debugging": false,
    "userExternalId": "http://www.johnadmin.cz"
}
