### ISSUE TITLE
Link processing DPU

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#43]
#### Description
Schedule linking jobs from a DPU. The DPU should include a list of available processors and selection of source datasets.
#### DoD
User is able to configure and schedule link process without knowing the technical details.
#### Testing
BDD tests

**Comment by jkesanie** [comment]
First version that kind of works. Jenkins pipeline added and added the resulting artifact as part of the attx-uv-dpus image.

**Comment by blankdots** [comment]
Followup issues: 
* https://github.com/ATTX-project/graph-component/issues/24
* some unit tests might be beneficial but were not part of the original task definition
* assuming BDD tests will be handled by a another issue ?

We might need to change these lines in the testing environment: 
* https://github.com/ATTX-project/workflow-component/blob/dev/unifiedViews/uv-dpu-l-attx-linker/src/main/java/org/uh/hulib/attx/wc/uv/dpu/linker/LinkerConfig_V1.java#L19
* https://github.com/ATTX-project/workflow-component/blob/dev/unifiedViews/uv-dpu-l-attx-linker/src/main/java/org/uh/hulib/attx/wc/uv/dpu/linker/LinkerConfig_V1.java#L20

----------

Testing scenario:

1. Build docker-compose file in `platform-deployment/dcompose` with `gradle -PregistryURL=attx-dev:5000 -PartifactRepoURL=http://attx-dev:8081 CCF` (if local build)
2.  start with `docker-compose -f build/docker-compose.yml up`
3. Check the plugin is added to Unifiedviews and can load strategies
4. Finish with `gradle removeImages` - cleaning used images

**Comment by jkesanie** [comment]
The values Stefan refers are default values that can be changed. For testing one can create a new pipeline with custom values and then export it.
