### ISSUE TITLE
Decide how to refactor WF api to UV provenance API or to something simpler

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/workflow-component#50]
#### Description
Refactor WF-API to address v2.0 of the architecture as illustrated in https://attx-project.github.io/ATTX-Architecture-Overview.html
#### DoD

Decision on implementation details + new issues

#### Testing
Peer-review

**Comment by blankdots** [comment]
To include information about Public and Private pipelines and successful or unsuccessful executions in the response as mentioned in https://github.com/ATTX-project/graph-component/issues/20#issuecomment-312193009

**Comment by blankdots** [comment]
The need for such a Provenance API was to:
* get start and end times for the execution of the pipelines: PROPOSED Solution - have the DPUs of the pipelines send this information
* get the status for the execution of the pipelines: PROPOSED Solution - have the DPUs of the pipelines send this information
* get the DPU configuration in a pipeline: PROPOSED Solution - have the DPUs of the pipelines send this information
* get the privacy status of a pipeline
* sequence of steps: PROPOSED Solution - have Provenance Service generate this information

@jkesanie thoughts or something missing?

**Comment by jkesanie** [comment]
Regarding status of the workflow execution, we must come up with a solution to identify failed executions somehow.

**Comment by jkesanie** [comment]
We do need the UV provenance because it is the only way to get information about the execution of DPUs that *don't* use the ATTX platform services. Examples would be simple trimming operations or find-and-replace operations based on downloaded files.

**Comment by blankdots** [comment]
Considering this need the next version of the UV-Provenance API should/must be able to:
* work with messaging service
* provide as output similar message as described in https://github.com/ATTX-project/provenance-service/issues/5
* keep track of the workflow executions for which provenance information has been generated
* Check if there are any finished executions for which the provenance has not been registered
* work with the DB in order to get status and necessary DPU's configuration
* Provide explicit provenance related to UnifiedViews and its components (e.g. repository for DPUs, parsing the configuration of certain DPUs etc.)

**Comment by blankdots** [comment]
follow-up issue https://github.com/ATTX-project/workflow-component/issues/56
