### ISSUE TITLE
Update attx-dpus-image to work with the latest UV

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/workflow-component#52]
#### Description
Image should work in the following environment:
* kontena
* local PC
* Jenkins tests

#### DoD
Tagged image that works in the listed environments

#### Testing
Integration tests

**Comment by blankdots** [comment]
As mentioned in https://github.com/ATTX-project/platform-deployment/issues/46#issuecomment-310963342
There are new tags that have been tested with https://github.com/ATTX-project/elag2017-demo docker swarm.

**Comment by blankdots** [comment]
Working Kontena yml file with new UV-ATTX-DPUs image https://github.com/ATTX-project/platform-deployment/blob/feature-kontena/attx-kontena/attx-kontena.yml
